services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "3001:5173"
    depends_on:
      - auth-service

  auth-service:
    image: python:3.12
    working_dir: /app
    volumes:
      - ./app:/app
      - ./logs/auth-service:/app/logs
    command: sh -c "pip install -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/authdb
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=authdb
    ports:
      - "${DB_PORT}:3306"

  prometheus: # possède prometheus-fastapi-instrumentor pour exposer les métriques de l'application
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT}:9090"
    depends_on:
      - auth-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  node-exporter: # Si le temps, ajouter node_exporter pour les infos du conteneur, voir pour mettre alertmanager
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"

volumes:
  db-data:
  grafana-data: